# Generated by Django 4.2 on 2024-09-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePlaza',
            fields=[
                ('ID_DetallePlaza', models.AutoField(primary_key=True, serialize=False)),
                ('Valor', models.CharField(max_length=50, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Detalle Plaza',
            },
        ),
    ]
