# Generated by Django 4.2 on 2024-09-25 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamentos.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
            },
        ),
    ]
