# Generated by Django 4.2 on 2024-09-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('ID_Cargo', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(max_length=20, unique=True, verbose_name='Cargo')),
                ('Nombre_cargo', models.CharField(max_length=100, verbose_name='Nombre Cargo')),
            ],
        ),
    ]
