# Generated by Django 4.2 on 2024-09-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDetalle',
            fields=[
                ('ID_LISTA_DETALLE', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('Descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('Fecha_Creacion', models.DateField(verbose_name='Fecha Creación')),
            ],
        ),
    ]
