# Generated by Django 4.2 on 2024-09-25 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postulante', '0001_initial'),
        ('habilidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleHabilidades',
            fields=[
                ('ID_DetalleHabilidades', models.AutoField(primary_key=True, serialize=False)),
                ('Valor', models.CharField(max_length=100, verbose_name='Valor')),
                ('ID_Habilidades', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='habilidades.habilidades')),
                ('ID_Postulante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postulante.postulante')),
            ],
            options={
                'verbose_name': 'Detalle Habilidades',
            },
        ),
    ]
